# Versions
el_major_version: 7
el_minor_version: 7
el_version: '{{ el_major_version }}.{{ el_minor_version }}'
centos_release: '1908'
centos_version: '{{ el_version }}.{{ centos_release }}'
ohpc_major_version: 1
ohpc_minor_version: 3
ohpc_version: '{{ ohpc_major_version }}.{{ ohpc_minor_version }}'

#
vydog_root: /opt/versatushpc/vydog/
iso_path: /root/
centos_iso: CentOS-{{ el_major_version }}-x86_64-DVD-{{ centos_release }}.iso

fqdn: '{{ cluster_name }}.{{ domain_name }}'

# Postfix configuration
postfix_myhostname: '{{ cluster_name }}'
postfix_mydomain: '{{ domain_name }}'
postfix_mydestination: []
postfix_mynetworks:
  - 127.0.0.0/8
  - '[::1]/128'
  - '{{ sms_network }}'

# Zabbix role variables
agent_server: 'zabbix.versatushpc.com.br'
agent_serveractive: '{{ agent_server }}'
zabbix_version: 3.4


# FreeIPA variables
ipaserver_hostname: '{{ fqdn }}'
ipaserver_domain: '{{ domain_name }}'
ipaserver_realm: '{{ domain_name | upper }}'
ipaserver_setup_dns: yes
ipaserver_no_ui_redirect: yes
ipaserver_reverse_zones: ['{{ sms_ip | reverse_name }}']
ipaserver_auto_forwarders: yes
ipaclient_mkhomedir: yes

# Test avoid early failures to make running multiple times better to test
test: no

# CentOS Vault version to pin
centos_vault_version: 7.6.1810

# Versatus variables
versatus_hpc_ip: 179.228.138.121/32

# xCAT variables
pkglist: "/opt/versatushpc/xcat/compute.pkglist"
genimage_name: centos7.7-x86_64-netboot-compute
synclist: "/opt/versatushpc/xcat/compute.synclist"
chroot: "/install/netboot/centos{{ el_version }}/x86_64/compute/rootimg/"
