#!/bin/bash -ex

domain_to_basedn() {
    for i in $(echo $1 | tr -s . ' '); do
        echo -n dc=$i,;
    done | sed -e 's/,$//';
}

exec 1> >(logger -s -t xCAT -p local4.info) 2>&1

mkdir -p /etc/{ipa,ssh,sssd,openldap}/

: ${DHCPINTERFACES:=headnode.cluster.example.com|eth1} # fallback for testing

domain="$(hostname -d)"
nodename="$(hostname --fqdn)"
basedn="$(domain_to_basedn $domain)"
headnode="${DHCPINTERFACES%|*}" # this came from xCAT site table
realm="${domain^^}"

# https://access.redhat.com/articles/2622831

# Configure SSSD to point to the IdM domain by saving the following configuration in the /etc/sssd/sssd.conf file:
cat <<EOF >  /etc/sssd/sssd.conf 
[sssd]
config_file_version = 2
services = nss, pam, sudo

domains = $domain
[nss]

[pam]

[domain/$domain]
cache_credentials = True
krb5_store_password_if_offline = True
ipa_domain =$domain
id_provider = ipa
auth_provider = ipa
access_provider = ipa
ipa_hostname = $nodename
chpass_provider = ipa
ipa_server = $headnode
ldap_tls_cacert = /etc/ipa/ca.crt
EOF
chmod 600 /etc/sssd/sssd.conf

authconfig --update --enablesssd --enablesssdauth

cat <<EOF > /etc/krb5.conf
includedir /var/lib/sss/pubconf/krb5.include.d/

[libdefaults]
  default_realm = $realm
  dns_lookup_realm = true
  dns_lookup_kdc = true
  rdns = false
  ticket_lifetime = 24h
  forwardable = yes
  udp_preference_limit = 0
  default_ccache_name = KEYRING:persistent:%{uid}

[realms]
  $realm = {
    pkinit_anchors = FILE:/etc/ipa/ca.crt

  }

[domain_realm]
  .$domain = $realm
  $domain = $realm
EOF

curl -o /etc/ipa/ca.crt http://$headnode/ipa/config/ca.crt
certutil -A -d /etc/ipa/nssdb -n "IPA CA" -t CT,C,C -a -i /etc/ipa/ca.crt 
systemctl start certmonger.service
systemctl enable certmonger.service
ipa-getcert request -d /etc/pki/nssdb -n Server-Cert -K HOST/$nodename -N "CN=$nodename,O=$realm"
authconfig --nisdomain=client.example.com --update
systemctl restart rhel-domainname.service

cat <<EOF >>  /etc/nsswitch.conf
sudoers: files sss
EOF
systemctl restart sssd.service

