- name: Clone Spack
  shell: |
    git clone https://bitbucket.versatushpc.com.br/scm/pkg/spack.git /opt/spack
  register: git
  failed_when: git.rc != 0 and git.stderr is not search("already exists")

- name: Create profile file
  copy:
    dest: /etc/profile.d/versatushpc-spack.sh
    mode: '0755'
    content: |
      #!/bin/sh
      if [ $EUID -eq 0 ] ; then
          source /opt/spack/share/spack/setup-env.sh
          source /opt/spack/share/spack/spack-completion.bash
      else
          export MODULEPATH=/opt/spack/share/spack/modules/linux-centos7-x86_64:$MODULEPATH
      fi

      export LMOD_IGNORE_CACHE=1

- name: Add compilers
  shell: |
    source /etc/profile.d/versatushpc-spack.sh
    spack compiler add /opt/ohpc/pub/compiler/gcc/8.3.0

- name: Export folders with NFS
  lineinfile:
    dest: /etc/exports
    line: /opt/spack *(ro)

- name: Export folder
  shell: exportfs -a

- name: Enable the directories on IPA with automount
  shell: |
    kinit admin <<< {{ ipaadmin_password }}
    ipa automountmap-add compute auto.spack
    ipa automountkey-add compute auto.master --key=/opt/spack --info=auto.spack
    ipa automountkey-add compute auto.spack --key="*" --info="-fstype=nfs headnode.cluster.example.com:/opt/spack/&"
    ipa automountlocation-tofiles compute



