- name: Load nodes variables
  include_vars:
    file: nodes.yml

- name: Add ipa-client
  copy:
    src: templates/ipa-client
    dest: /opt/versatushpc/xcat/postscripts/ipa-client
    mode: '0755'

- name: Add postscripts
  shell: |
    source /etc/profile.d/xcat.sh
    chdef -t osimage -o centos7.6-x86_64-netboot-compute postscripts=versatushpc/ipa-client,versatuhpc/freeipa-automount-compute

- name: Create a Hostgroup with all the Compute Nodes inside FreeIPA
  shell: |
    ipa hostgroup-add --desc="Compute Nodes" compute
  register: cmd
  failed_when: cmd.rc != 0 && cmd.stderr | regex_search("already exists") 

- name: Create host
  loop_control:
    index_var: i
  loop: '{{ nodes }}'
  shell: |
    echo {{ ipaadmin_password }} | kinit admin
    echo {{ i | node_ip }}
    ipa host-add --ip-address={{ i | node_ip }} {{ i | node_name }}.{{ domain_name }}
    ipa host-add-managedby --hosts={{ fqdn }} {{ i | node_name }}.{{ domain_name }}
    ipa-getkeytab -s {{ fqdn }} -D "cn=Directory Manager" -w {{ ipaadmin_password }} -p host/{{ i | node_name }}.{{ domain_name }} -k /opt/versatushpc/etc/{{ i | node_name }}-krb5.keytab
    ipa hostgroup-add-member --hosts={{ i | node_name }}.{{ domain_name }} compute

- name: Setup Headnode as a client only to the compute nodes
  lineinfile:
    path: /etc/ssh/ssh_config
    line: '{{ item }}'
  loop:
    - HostbasedAuthentication yes
    - EnableSSHKeysign yes

- name: Create postinstall script
  copy:
    mode: '0755'
    dest: /opt/versatushpc/xcat/postinstall/hostbased-auth.sh
    content: |
      #!/bin/sh -x

      # Generate the shared DSA, RSA, ECDSA and ED25519 host keys inside the image

      setenforce 0
      test -f $IMG_ROOTIMGDIR/etc/ssh/ssh_host_dsa_key     || ssh-keygen -f $IMG_ROOTIMGDIR/etc/ssh/ssh_host_dsa_key     -N '' -t dsa     -C "Shared hostkey for Hostbased Authentication"
      test -f $IMG_ROOTIMGDIR/etc/ssh/ssh_host_rsa_key     || ssh-keygen -f $IMG_ROOTIMGDIR/etc/ssh/ssh_host_rsa_key     -N '' -t rsa     -C "Shared hostkey for Hostbased Authentication"
      test -f $IMG_ROOTIMGDIR/etc/ssh/ssh_host_ecdsa_key   || ssh-keygen -f $IMG_ROOTIMGDIR/etc/ssh/ssh_host_ecdsa_key   -N '' -t ecdsa   -C "Shared hostkey for Hostbased Authentication"
      test -f $IMG_ROOTIMGDIR/etc/ssh/ssh_host_ed25519_key || ssh-keygen -f $IMG_ROOTIMGDIR/etc/ssh/ssh_host_ed25519_key -N '' -t ed25519 -C "Shared hostkey for Hostbased Authentication"
      setenforce 1

      # Configure Image Clientside
      grep -E '^HostbasedAuthentication yes' || echo 'HostbasedAuthentication yes' >> $IMG_ROOTIMGDIR/etc/ssh/ssh_config
      grep -E '^EnableSSHKeysign yes'        || echo 'EnableSSHKeysign yes'        >> $IMG_ROOTIMGDIR/etc/ssh/ssh_config

      # Configure Image Serverside
      test -f $IMG_ROOTIMGDIR/etc/ssh/shosts.equiv || cat << EOF > $IMG_ROOTIMGDIR/etc/ssh/shosts.equiv
      {{ fqdn }}
      @compute
      EOF

      sed -i s/#HostbasedAuthentication/HostbasedAuthentication/ $IMG_ROOTIMGDIR/etc/ssh/sshd_config

      # Create the known_hosts file with the keys:
      ssh-keyscan -H {{ fqdn }} > $IMG_ROOTIMGDIR/etc/ssh/ssh_known_hosts
       
      export DSA_KEY=`cat $IMG_ROOTIMGDIR/etc/ssh/ssh_host_dsa_key.pub | cut -f 2 -d " "`
      export RSA_KEY=`cat $IMG_ROOTIMGDIR/etc/ssh/ssh_host_rsa_key.pub | cut -f 2 -d " "`
      export ECDSA_KEY=`cat $IMG_ROOTIMGDIR/etc/ssh/ssh_host_ecdsa_key.pub | cut -f 2 -d " "`
      export ED25519_KEY=`cat $IMG_ROOTIMGDIR/etc/ssh/ssh_host_ed25519_key.pub | cut -f 2 -d " "`
       
      grep -E '{{ nodes_prefix }}' $IMG_ROOTIMGDIR/etc/ssh/ssh_known_hosts || echo "{{ nodes_prefix }}* ssh-ed25519 $ED25519_KEY"       >> $IMG_ROOTIMGDIR/etc/ssh/ssh_known_hosts
      grep -E '{{ nodes_prefix }}' $IMG_ROOTIMGDIR/etc/ssh/ssh_known_hosts || echo "{{ nodes_prefix }}* ecdsa-sha2-nistp256 $ECDSA_KEY" >> $IMG_ROOTIMGDIR/etc/ssh/ssh_known_hosts
      grep -E '{{ nodes_prefix }}' $IMG_ROOTIMGDIR/etc/ssh/ssh_known_hosts || echo "{{ nodes_prefix }}* ssh-rsa $RSA_KEY"               >> $IMG_ROOTIMGDIR/etc/ssh/ssh_known_hosts
      grep -E '{{ nodes_prefix }}' $IMG_ROOTIMGDIR/etc/ssh/ssh_known_hosts || echo "{{ nodes_prefix }}* ssh-dss $DSA_KEY"               >> $IMG_ROOTIMGDIR/etc/ssh/ssh_known_hosts

- name: Add postinstall script to the image
  shell: |
    source /etc/profile.d/xcat.sh
    chdef -t osimage -o centos7.6-x86_64-netboot-compute -p postinstall=/opt/versatushpc/xcat/postinstall/hostbased-auth.sh

- name: Add keytab to synclists
  lineinfile:
    create: yes
    path: /opt/versatushpc/xcat/centos7.6-compute.synclist
    line: '/opt/versatushpc/etc/{{ i | node_name }}-krb5.keytab -> ({{ i | node_name }}) /etc/krb5.keytab'
  loop: '{{ nodes }}'
  loop_control:
    index_var: i
    loop_var: node

- name: Add syncfiles to the image
  shell: |
    source /etc/profile.d/xcat.sh
    chdef -t osimage -o centos7.6-x86_64-netboot-compute synclists="/opt/versatushpc/xcat/centos7.6-compute.synclist"
