- hosts: sms
  gather_facts: no
  vars:
    skip_questions: yes
  tasks:
    - name: Download CentOS
      get_url:
        url: http://mirror.cc.if.ufrj.br/iso/CentOS-7-x86_64-DVD-1810.iso
        dest: /root/CentOS-7-x86_64-DVD-1810.iso

    - name: Generate Image
      shell: |
        source /etc/profile.d/xcat.sh
        copycds /root/CentOS-7-x86_64-DVD-1810.iso

    - name: Create diretory
      file:
        state: directory
        path: /install/custom/postinstall/centos7.6/

    - name: Create add-cluster-key.sh postinstall
      copy:
        dest: /install/custom/postinstall/centos7.6/add-cluster-key.sh
        mode: '0755'
        content: |
          #!/bin/bash
          pubkey=$(cat ~/.ssh/id_ed25519.pub)
          authorized_keys="$IMG_ROOTIMGDIR/root/.ssh/authorized_keys"
          if [ ! -f $authorized_keys ]; then
              mkdir -p $IMG_ROOTIMGDIR/root/.ssh || : # ignore error
              chmod 0700 $IMG_ROOTIMGDIR/root/.ssh
              echo "$pubkey" >> $authorized_keys
          else
              grep "$pubkey" $authorized_keys || echo "$pubkey" >> $authorized_keys
          fi

    - name: Add postinstall to the image
      shell: |
        source /etc/profile.d/xcat.sh
        chdef -t osimage -o centos7.6-x86_64-netboot-compute -p postinstall=/install/custom/postinstall/centos7.6/add-cluster-key.sh

    - name: Create pkglist folder
      file:
        state: directory
        path: /install/custom/netboot/centos7.6/

    - name: Add freeipa-client to the image
      lineinfile:
        create: yes
        path: /install/custom/netboot/centos7.6/compute.pkglist
        line: freeipa-client

    - name: Add compute.pkglist to the image
      shell: |
        source /etc/profile.d/xcat.sh
        chdef -t osimage -o centos7.6-x86_64-netboot-compute -p pkglist=/install/custom/netboot/centos7.6/compute.pkglist

    - name: Add repositorioes to the image
      shell: |
        source /etc/profile.d/xcat.sh
        chdef -t osimage -o centos7.6-x86_64-netboot-compute -p pkgdir=http://vault.centos.org/7.6.1810/os/x86_64/
        chdef -t osimage -o centos7.6-x86_64-netboot-compute -p pkgdir=http://vault.centos.org/7.6.1810/updates/x86_64/
        chdef -t osimage -o centos7.6-x86_64-netboot-compute -p pkgdir=http://vault.centos.org/7.6.1810/extras/x86_64/
        chdef -t osimage -o centos7.6-x86_64-netboot-compute -p pkgdir=http://download.fedoraproject.org/pub/epel/7/x86_64
        chdef -t osimage -o centos7.6-x86_64-netboot-compute -p pkgdir=http://build.openhpc.community/OpenHPC:/1.3/CentOS_7
        chdef -t osimage -o centos7.6-x86_64-netboot-compute -p pkgdir=http://build.openhpc.community/OpenHPC:/1.3/updates/CentOS_7
