---
- hosts: sms
  gather_facts: yes
  pre_tasks:
    - package_facts:
        manager: auto
  tasks:
    # https://confluence.versatushpc.com.br/display/DEPLOY/Pre-requisite://confluence.versatushpc.com.br/display/DEPLOY/Pre-requisites
    - assert:
        that:
          ansible_version.full >= "2.8.0"
    - import_role: name=checks
    - import_role: name=prereqs
    - import_role: name=network
    - import_role: name=versatus
    - import_role: name=base-system
    - import_role: name=add-image
    - import_role: name=infiniband
    - import_role: name=basic-openhpc
    - include_role: name=slurm
      when: queue_system == "slurm"
    - include_role: name=pbs
      when: queue_system == "pbs"
    - import_role: name=ganglia
    - import_role: name=postfix
    - import_role: name=spack
    - import_role: name=latex-support
    - import_role: name=define-nodes
