---
- hosts: sms
  gather_facts: yes
  pre_tasks:
    - package_facts:
        manager: auto
  tasks:

    - block:
      - include_tasks: test/ovirt-test.yml
      - setup:
      when: test_snap is defined and test_snap == 'yes'

    # Prereqs
    - name: Check system version
      assert:
        that:
          ansible_facts.distribution == "CentOS" and
          ansible_facts.distribution_version == "7.6"

    - name: Cleanup hosts
      copy:
        content: |
          127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
          ::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
        dest: /etc/hosts

    - name: Enable CentOS Vault
      include_role:
        name: centos-vault
      when: ansible_facts.distribution == "CentOS"

    # Network configuration
    - name: Set hostname
      hostname:
        name: '{{ fqdn }}'

    - name: Test DNS resolution
      block:
        - yum: name=bind-utils state=present
        - shell: host example.com
          changed_when: false

    # Base system

    - include_role:
        name: roles/freeipa/roles/ipaserver
      vars:
        state: present
      when: "'ipa-server' not in ansible_facts.packages"

    - include_role:
        name: xcat
      when: "'xCAT' not in ansible_facts.packages"

