- hosts: sms
  gather_facts: no
  vars:
    skip_questions: yes
  pre_tasks:
    - name: Get package facts
      package_facts:
        manager: auto
  tasks:
    - include_role: name=pbs
      when: queue_system == "pbs"
