- name: Add repo to the image
  shell: |
    source /etc/profile.d/xcat.sh
    chdef -t osimage -o {{ genimage_name }} -p pkgdir=http://linux.mellanox.com/public/repo/mlnx_ofed_dpdk_upstream_libs/latest/rhel{{ el_version }}/x86_64
  notify: xcat genimage
  tags:
    - postinstall


- name: Add packages to the image
  lineinfile:
    state: present
    line: '{{ item }}'
    dest: '{{ pkglist }}'
  loop:
    - mlnx-ofed-dpdk-upstream-libs
    - infinipath-psm
  notify: xcat genimage
  tags:
    - genimage 

