- name: Load nodes variables
  include_vars:
    file: nodes.yaml

- name: Check that nodes are defined
  assert:
    that:
      - nodes is defined

- name: Configure Infiniband for computing nodes
  when: ib_stack is defined and ib_stack != "none"
  loop: '{{ nodes }}'
  loop_control:
    index_var: i
    loop_var: node
  ignore_errors: yes
  shell: |
    source /etc/profile.d/xcat.sh
    chdef -t node {{ i | node_name }} nicips.ib0={{ i | node_ib_ip }} nicnetworks.ib0=application nictypes.ib0=InfiniBand

- name: Configure Infiniband for head node
  when: ib_stack is defined and ib_stack != "none"
  ignore_errors: yes
  shell: |
    source /etc/profile.d/xcat.sh
    chdef -t network -o application mask={{ ib_network | ipaddr('netmask') }} net={{ ib_network }} mtu=2044
    chdef compute -p postbootscripts=confignics
