- name: Create OpenCATTUS directories
  file:
    state: directory
    path: "{{ opencattus_path }}/etc"
    mode: '0755'

- name: Create versatushpc-release file
  copy:
    dest: "{{ opencattus_path }}/etc/release"
    content: |
      RELEASE=0.1-DEVELOPMENT
      VENDOR=
      CONTRACT_NUMBER=
      INSTALLER_NAME=
      DEPLOY_STATUS=
      RAS_START_DATE=
      RAS_END_DATE=
      CONTACT=
      LOCATION=
      NOTES=

- name: Add VersatusHPC IP address as allowed on public firewall zone
  when: versatushpc_access_enabled
  firewalld:
    zone: public
    source: "{{ versatus_hpc_ip }}"
    state: enabled
    permanent: yes

- name: Reload firewalld
  systemd:
    name: firewalld
    state: reloaded

- name: Create custom motd
  template:
    dest: /etc/motd
    src: motd.j2

- name: Create /root/.ssh directory
  file:
    state: directory
    path: /root/.ssh
    mode: '0755'

- name: Create authorized_keys
  when: versatushpc_access_enabled
  lineinfile:
    path: /root/.ssh/authorized_keys
    mode: '0700'
    create: yes
    line: "{{ item }}"
  loop:
    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIF9dM32vl7oMAI3H4aAgtSINRYc69+v9y4UobTiRX7b+ angelo
    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILvv3VhslrVwZEpnK/sjJMs5AxH7EuaJYBTliKgXrVCL denis
    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHEe84J84HpTAXZe7WNsxWtmacT1zBov+u6Q94wbOdiq eiji
    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIlAXfqgsQSNGqbyIFDNucUTU9PfZXvcjPE3iph9eWjL fabricio
    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBD1qtOpSgWSZAgqzBLhk0Rv6uCyLOJG2XY9o9SX0Y1H ferrao
    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHtewyz5PydEwYO8saMbywUEeuORzUkXq3owlwVuc+VF hilst
    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBbdZaCeETGnREjn5O8hB90QTFX5d6DyEG5u0BhboBEd nelson

- name: Restore SELinux contexts on /root/.ssh
  shell: restorecon -R /root/.ssh
