---
# handlers file for ganglia
- import_tasks: ../../xcat/handlers/main.yaml

- name: enable http and https in firewall
  firewalld:
    state: enabled
    permanent: yes
    service: '{{ item }}'
  with_items:
    - https
    - http

- name: restart httpd
  service:
    name: httpd
    state: restarted

- name: restart gmond and gmetad
  systemd:
    state: restarted
    name: '{{ item }}'
  loop:
    - gmond
    - gmetad
