---
# handlers file for ganglia
- name: enable http and https in firewall
  firewalld:
    state: enabled
    permanent: yes
    service: '{{ item }}'
  with_items:
    - https
    - http

- name: restart httpd
  service:
    name: httpd
    state: restarted

- name: xcat genimage
  shell: |
    source /etc/profile.d/xcat.sh
    genimage {{ genimage_name }}
    packimage {{ genimage_name }}

- name: restart gmond and gmetad
  systemd:
    state: restarted
    name: '{{ item }}'
  loop:
    - gmond
    - gmetad
