- name: Enable xCAT repos
  shell: |
    yum-config-manager --enable xcat-dep
    yum-config-manager --enable xcat-core

- name: Install xCAT
  yum:
    name: xCAT
    state: present

- selinux:
    state: enforcing
    policy: targeted

- systemd:
    name: firewalld
    enabled: yes
    state: started
