- name: Remove ~/.ssh/config created by xCAT
  file:
    state: absent
    path: ~/.ssh/config

- openssh_keypair:
    type: ed25519
    comment: Default root keypair for cluster authentication
    path: /root/.ssh/id_ed25519
