- name: Create SELinux policy file for xCAT
  copy:
    content: |
      module xCAT-httpd-read-tftpdir 1.0;

      require {
          type httpd_t;
          type tftpdir_t;
          class dir read;
          class file { getattr open read };
      }

      #============= httpd_t ==============
      allow httpd_t tftpdir_t:dir read;
      allow httpd_t tftpdir_t:file { getattr open read };
    dest: /root/xCAT-httpd-read-tftpdir.te

- name: Install SELinux policy file for xCAT
  shell: |
    checkmodule -M -m -o /root/xCAT-httpd-read-tftpdir.mod /root/xCAT-httpd-read-tftpdir.te
    semodule_package -o /root/xCAT-httpd-read-tftpdir.pp -m /root/xCAT-httpd-read-tftpdir.mod
    semodule -i /root/xCAT-httpd-read-tftpdir.pp

    semanage fcontext -a -t httpd_sys_content_t '/install(/.*)?'
    restorecon -R /install
    rm -rf /root/xCAT-httpd-read-tftpdir*
