- name: xCAT Setup site
  shell: |
    /opt/xcat/bin/chdef -t site \
      "dhcpinterfaces={{ fqdn }}|{{ sms_eth_internal }}" \
      domain={{ domain_name }} \
      FQDNfirst=1 \
      externaldns=1

