- name: Add OpenHPC repositories
  copy: 
    dest: /etc/yum.repos.d/OpenHPC.repo
    content: |
      [OpenHPC]
      name=OpenHPC-{{ ohpc_version }} - Base
      baseurl=http://build.openhpc.community/OpenHPC:/{{ ohpc_version }}/CentOS_{{ el_major_version }}
      gpgcheck=1
      gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-OpenHPC-1
      enabled=0
       
      [OpenHPC-updates]
      name=OpenHPC-{{ ohpc_version }} - Updates
      baseurl=http://build.openhpc.community/OpenHPC:/{{ ohpc_version }}/updates/CentOS_{{ el_major_version }}
      gpgcheck=1
      gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-OpenHPC-1
      enabled=0
       
      [OpenHPC-Sources]
      name=OpenHPC-{{ ohpc_version }} - Sources
      baseurl=http://build.openhpc.community/OpenHPC:/{{ ohpc_version }}/sources/CentOS_{{ el_major_version }}
      gpgcheck=1
      gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-OpenHPC-1
      enabled=0

- name: OpenHPC keys
  copy:
    dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-OpenHPC-1
    content: |
      -----BEGIN PGP PUBLIC KEY BLOCK-----
      Version: GnuPG v2

      mI0EVi/f0QEEAMdQnJVniOafZQ785EOdrTI0GQuranOyc3NqpNU3YDEfaqD7QMDS
      cb1blIe+G6LdfDqMqWbEqUyBtPSOXChAUryT7KP/Ue+tTTYoEioBW28/HsUKVNX5
      oUkuo71W+UPBq4TTO5QRixMfm7nlDz7xYJCcgX4tbuRqmmWYpmc+4QxFABEBAAG0
      KE9wZW5IUEMgQnVpbGQgU2VydmljZSA8b2JzcnVuQGxvY2FsaG9zdD6IuQQTAQIA
      IwUCVi/f0QIbAwcLCQgHAwIBBhUIAgkKCwQWAgMBAh4BAheAAAoJEMRoB/8mzmiE
      pXkEAJaAou2ihJX6DCUy7q+Keqm5pDgnUZTlyRM6zzHVVXX5HM6K6BmNenXPoXlm
      br3KJQ6Lq5yMQSBAJgXF9j+bfNWTG8xnT+4GXclQl8CDiBCVKdvypoAqo9GBkJFf
      +9UA0AI8rei8R8SSMPDkblpiOXqjn/hS7s5paE47agtuJNq6uI0EVi/f0QEEALz4
      ddFrPWnXJ8kBV52EkdjSoQP+pqf8qevJ9/lcsVfQx+160E6cKx1VLdWMo15D/Tix
      DxwpKaEKGptnD4Owl5VjSB2S+UIgda6Xw4VQTbJH2d5ERXDDsjXk3yN29i+rahKR
      iiq1+9W8fsmUdUzxYA/NYjpVZyxOFW5heiok9bKpABEBAAGInwQYAQIACQUCVi/f
      0QIbDAAKCRDEaAf/Js5ohLB+A/4lNfnjNEYV0vhNV6swRIK8z4CfUFUfVRncLw+R
      WlOv0/bj8DaAD68yhVFuXBThJ1ONG5+9Z04BeXzgYIBgfQ+8tBnT1KTcfD+898qP
      H/jM2HXWGQFie5oEdvnvq21SQG7M87IQjmW9eOzMWfzMGZV+7pJW3xvh8gqxd1Sw
      Or6r3w==
      =mEMt
      -----END PGP PUBLIC KEY BLOCK-----

- name: OpenHPC import key
  rpm_key:
    state: present
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-OpenHPC-1
