- name: Install xCAT dep repo
  copy:
    dest: /etc/yum.repos.d/xcat-dep.repo
    content: |
      [xcat-dep]
      name=xCAT 2 depedencies
      baseurl=http://xcat.org/files/xcat/repos/yum/xcat-dep/rh7/x86_64
      enabled=0
      gpgcheck=1
      gpgkey=http://xcat.org/files/xcat/repos/yum/xcat-dep/rh7/x86_64/repodata/repomd.xml.key

- name: Install xCAT core repo
  copy:
    dest: /etc/yum.repos.d/xcat-core.repo
    content: |
      [xcat-core]
      name=xCAT 2 Core packages
      baseurl=http://xcat.org/files/xcat/repos/yum/latest/xcat-core
      enabled=0
      gpgcheck=1
      gpgkey=http://xcat.org/files/xcat/repos/yum/latest/xcat-core/repodata/repomd.xml.key
