- assert:
    that:
      - nodes is defined

- name: Setup Nodes
  loop: "{{ nodes }}"
  loop_control:
    index_var: i
    loop_var: node
  ignore_errors: yes
  shell: |
    source /etc/profile.d/pbs.sh
    qmgr -c "create node {{ i | node_name }}"
