- name: Remove from xCAT DHCP
  shell: |
    source /etc/profile.d/xcat.sh
    makedhcp -d {{ node }}
  register: makedhcp
  failed_when: 'makedhcp.rc != 0 and makedhcp.stderr is not search("Error: Invalid nodes and/or groups in noderange")'

- name: Remove from PBS
  when: queue_system == "pbs"
  shell: |
    source /etc/profile.d/pbs.sh
    qmgr -c "delete node {{ node }}"

- name: Remove from Slurm
  when: queue_system == "slurm"
  lineinfile:
    dest: /etc/slurm/slurm.conf
    state: absent
    regex: '^NodeName={{ node }}'

- name: Remove keytab from compute.synclist
  lineinfile:
    state: absent
    path: "{{ synclist }}"
    line: "{{ opencattus_path }}/etc/{{ node }}-krb5.keytab -> ({{ node }}) /etc/krb5.keytab"

- name: Delete keytab
  file:
    state: absent
    path: "{{ opencattus_path }}/etc/{{ node }}-krb5.keytab"

- name: Remove host from hostgroup
  shell: |
    kinit admin <<< "{{ ipadm_password }}"
    ipa hostgroup-del compute {{ node }}.{{ domain_name }}
    ipa host-del {{ node }}.{{ domain_name }} --updatedns
  register: hostgroup
  failed_when: 'hostgroup.rc != 0 and (hostgroup.stdout | regex_search("(host (group)? not found)", multiline=True) == "")'
  changed_when: 'hostgroup.rc == 0 and (hostgroup.stdout | regex_search("(host (group)? not found)", multiline=True) != "")'

  # - name: Get node IP
  #   shell: |
  #     set -o pipefail
  #     source /etc/profile.d/xcat.sh
  #     lsdef {{ node }} -i ip | sed 1d | cut -f2 -d=
  #   register: ip
  #   ignore_errors: yes
  #
  # - name: Remove DNS records
  #   when: not ip.failed
  #   shell: |
  #     kinit admin <<< "{{ ipadm_password }}"
  #     ipa dnsrecord-del --del-all {{ domain_name }} {{ node }}
  #     ipa dnsrecord-del {{ ip.stdout | reverse_name }} --ptr-rec={{ node }}.{{ domain_name }}.

- name: Remove host from xCAT
  shell: |
    source /etc/profile.d/xcat.sh
    nodepurge {{ node }}
  register: rmdef
  failed_when: 'rmdef.rc != 0 and rmdef.stderr is not search("Could not find an object named")'
  changed_when: 'rmdef.rc == 0 and rmdef.stdout is not search("No objects have been removed from the xCAT database")'
