---
- name: Check input
  assert:
    that:
      - centos_vault_version in centos_vault_supported_versions

- name: CentOS Vault repos
  copy:
    dest: /etc/yum.repos.d/CentOS-Vault.repo
    content: |
      # C7.6.1810
      [C7.6.1810-base]
      name=CentOS-7.6.1810 - Base
      baseurl=http://vault.centos.org/7.6.1810/os/\$basearch/
      gpgcheck=1
      gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
      enabled=0

      [C7.6.1810-updates]
      name=CentOS-7.6.1810 - Updates
      baseurl=http://vault.centos.org/7.6.1810/updates/\$basearch/
      gpgcheck=1
      gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
      enabled=0

      [C7.6.1810-extras]
      name=CentOS-7.6.1810 - Extras
      baseurl=http://vault.centos.org/7.6.1810/extras/\$basearch/
      gpgcheck=1
      gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
      enabled=0

      [C7.6.1810-centosplus]
      name=CentOS-7.6.1810 - CentOSPlus
      baseurl=http://vault.centos.org/7.6.1810/centosplus/\$basearch/
      gpgcheck=1
      gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
      enabled=0

      [C7.6.1810-fasttrack]
      name=CentOS-7.6.1810 - Fasttrack
      baseurl=http://vault.centos.org/7.6.1810/fasttrack/\$basearch/
      gpgcheck=1
      gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
      enabled=0

- import_tasks: install-yum-config-manager.yml

- name: Enable the Vault versions of Base, Updates and Extras repositories, keeping everything else disabled.
  shell: |
    yum-config-manager --disable \*
    yum-config-manager --enable C7.6.1810-{base,updates,extras}
