---
- name: Stop if IPA is already installed
  fail:
    msg: |
      FreeIPA is already installed, reinstalling is not supported, sorry.
    when: "ipa-server" in ansible_facts.packages

- include_role:
    name: ipaserver
  vars:
    state: present
  when: 'ipa-server' not in ansible_facts.packages


