- name: Enable automount with FreeIPA so the compute can mount the required filesystems
  shell: |
    echo {{ ipaadmin_password }} | kinit admin
    ipa automountlocation-add compute
    ipa automountmap-add compute auto.home
    ipa automountmap-add compute auto.ohpc
    ipa automountkey-add compute auto.home --key="*" --info="-fstype=nfs {{ fqdn }}:/home/&"
    ipa automountkey-add compute auto.ohpc --key="*" --info="-fstype=nfs {{ fqdn }}:/opt/ohpc/pub/&"
    ipa automountkey-add compute auto.master --key=/home --info=auto.home
    ipa automountkey-add compute auto.master --key=/opt/ohpc/pub --info=auto.ohpc
    ipa automountlocation-tofiles compute
  tags:
    - automount

- name: Create the automount script file to be run at each compute note boot process
  copy:
    dest: "{{ opencattus_path }}/xcat/postscripts/freeipa-automount-compute"
    content: |
      exec 1> >(logger -s -t xCAT -p local4.info) 2>&1
      touch /var/lib/ipa-client/sysrestore/.workaround # workaround on ipa-client-automount bug
      ipa-client-automount --location=compute --unattended
    mode: '0755'
  tags:
    - postscripts

- name: Add the auto mount script to xCAT defaults on compute nodes
  shell: |
    source /etc/profile.d/xcat.sh
    chdef -t osimage -o {{ genimage_name }} -p postscripts=opencattus/freeipa-automount-compute
  tags:
    - postscripts
