- name: Change the compute image to support OpenHPC
  yum:
    installroot: /install/netboot/centos7.6/x86_64/compute/rootimg
    name:
      - ohpc-base-compute
      - lmod-ohpc
      - ntp

- name: Config NTP in the image
  lineinfile:
    dest: /install/netboot/centos7.6/x86_64/compute/rootimg/etc/ntp.conf
    state: present
    regexp: "^server 0"
    line: "server {{ fqdn }}"

- name: Remove other NTP servers in the image
  lineinfile:
    dest: /install/netboot/centos7.6/x86_64/compute/rootimg/etc/ntp.conf
    state: absent
    regexp: "^server (?!{{ fqdn }})"
