- name: Create ipa-join postscript
  copy:
    dest: /opt/versatushpc/xcat/postscripts/ipa-join
    mode: '0755'
    content: |
      domain_to_basedn() {
          for i in $(echo $1 | tr -s . ' '); do
              echo -n dc=$i,;
          done | sed -e 's/,$//';
      }

      exec 1> >(logger -s -t xCAT -p local4.info) 2>&1

      mkdir -p /etc/{ipa,ssh,sssd,openldap}/

      domain="$(hostname -d)"
      nodename="$(hostname --fqdn)"
      basedn="$(domain_to_basedn $domain)"
      headnode=$(echo ${DHCPINTERFACES} | sed "s/'//g; s/\(.*\?\)|.*/\1/") # this came from xCAT site table
      realm="${domain^^}"

      # On the image
      cat > /etc/sssd/sssd.conf << EOF
      [domain/$domain]

      cache_credentials = True
      krb5_store_password_if_offline = True
      ipa_domain = $domain
      id_provider = ipa
      auth_provider = ipa
      access_provider = ipa
      ipa_hostname = $nodename
      chpass_provider = ipa
      ipa_server = _srv_, $headnode
      ldap_tls_cacert = /etc/ipa/ca.crt
      [sssd]
      services = nss, sudo, pam, ssh

      domains = $domain
      [nss]
      homedir_substring = /home

      [pam]

      [sudo]

      [autofs]

      [ssh]

      [pac]

      [ifp]

      [secrets]

      [session_recording]

      EOF

      chown root:root /etc/sssd/sssd.conf
      chmod 600 /etc/sssd/sssd.conf

      authconfig --update --enablesssd --enablesssdauth

      cat > /etc/krb5.conf << EOF
      includedir /etc/krb5.conf.d/
      includedir /var/lib/sss/pubconf/krb5.include.d/

      [libdefaults]
        default_realm = $realm
        dns_lookup_realm = true
        dns_lookup_kdc = true
        rdns = false
        dns_canonicalize_hostname = false
        ticket_lifetime = 24h
        forwardable = true
        udp_preference_limit = 0
        default_ccache_name = KEYRING:persistent:%{uid}


      [realms]
        $realm = {
          pkinit_anchors = FILE:/var/lib/ipa-client/pki/kdc-ca-bundle.pem
          pkinit_pool = FILE:/var/lib/ipa-client/pki/ca-bundle.pem

        }


      [domain_realm]
        .$domain                     = $realm
        $domain                      = $realm
        $nodename                    = $realm

      EOF

      curl -o /etc/ipa/ca.crt http://$headnode/ipa/config/ca.crt

      certutil -A -d /etc/ipa/nssdb -n "IPA CA" -t CT,C,C -a -i /etc/ipa/ca.crt

      systemctl start certmonger.service
      systemctl enable certmonger.service

      ipa-getcert request -d /etc/pki/nssdb -n Server-Cert -K HOST/$nodename -N "CN=$nodename,O=$realm"

      # This is weird; the NIS domain should be the domain and not the hostname:
      authconfig --nisdomain=$nodename --update

      cat >> /etc/nsswitch.conf << EOF

      sudoers: files sss

      EOF

      # My changes
      cat > /etc/ipa/default.conf << EOF
      [global]
      basedn = $basedn
      realm = $realm
      domain = $domain
      server = $headnode
      host = $nodename
      xmlrpc_uri = https://$headnode/ipa/xml
      enable_ra = True
      EOF

      cat >> /etc/openldap/ldap.conf << EOF
      URI ldaps://$headnode
      BASE $basedn
      TLS_CACERT /etc/ipa/ca.crt
      EOF

      cat >> /etc/ssh/ssh_config << EOF

      GlobalKnownHostsFile /var/lib/sss/pubconf/known_hosts
      PubkeyAuthentication yes
      ProxyCommand /usr/bin/sss_ssh_knownhostsproxy -p %p %h

      Host *
          GSSAPIAuthentication yes
      # If this option is set to yes then remote X11 clients will have full access
      # to the original X11 display. As virtually no X11 client supports the untrusted
      # mode correctly we set this to yes.
          ForwardX11Trusted yes
      # Send locale-related environment variables
          SendEnv LANG LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY LC_MESSAGES
          SendEnv LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT
          SendEnv LC_IDENTIFICATION LC_ALL LANGUAGE
          SendEnv XMODIFIERS
      EOF

      cat >> /etc/ssh/sshd_config << EOF
      KerberosAuthentication no
      PubkeyAuthentication yes
      UsePAM yes
      AuthorizedKeysCommand /usr/bin/sss_ssh_authorizedkeys
      GSSAPIAuthentication yes
      ChallengeResponseAuthentication yes
      AuthorizedKeysCommandUser nobody
      EOF

      systemctl start sssd
      systemctl enable sssd
      systemctl restart sshd

- name: Add ipa-join to image
  shell: |
    source /etc/profile.d/xcat.sh
    chdef -t osimage -o {{ genimage_name }} -p postscripts=versatushpc/ipa-join
