- name: Enable repos
  shell: |
    yum-config-manager --enable epel
    yum-config-manager --enable OpenHPC
    yum-config-manager --enable OpenHPC-updates

- name: Install yum-config-manager on the image
  yum:
    installroot: /install/netboot/centos7.6/x86_64/compute/rootimg
    disablerepo: '*'
    enablerepo: C7.6.1810-base
    name: yum-utils
    state: present

- name: Enable required repositories in the image too
  shell: |
    chroot /install/netboot/centos7.6/x86_64/compute/rootimg yum-config-manager --enable epel
    chroot /install/netboot/centos7.6/x86_64/compute/rootimg yum-config-manager --enable OpenHPC
    chroot /install/netboot/centos7.6/x86_64/compute/rootimg yum-config-manager --enable OpenHPC-updates

- name: Install the base and documentation packages
  yum:
    state: present
    name:
      - ohpc-base
      - docs-ohpc

- name: Check if NTP is running
  systemd:
    name: cronyd
    state: started

- name: Export the required filesystems over NFS
  copy:
    dest: /etc/exports
    content: |
      /home *(rw,no_subtree_check)
      /opt/ohpc/pub *(ro)

- import_tasks: automount.yml
- import_tasks: image.yml
