- name: Enable repos
  shell: |
    yum-config-manager --enable epel
    yum-config-manager --enable OpenHPC
    yum-config-manager --enable OpenHPC-updates

- name: Install the base and documentation packages
  yum:
    state: present
    name:
      - ohpc-base
      - docs-ohpc

- name: Check if chronyd is running
  systemd:
    name: chronyd
    state: started

- name: Export the required filesystems over NFS
  copy:
    dest: /etc/exports
    content: |
      /home *(rw,no_subtree_check)
      /opt/ohpc/pub *(ro)

- name: Call exportfs -a
  shell: |
    exportfs -a

- import_tasks: automount.yaml
- import_tasks: image.yaml
- import_tasks: development.yaml

