- name: Enable repos
  shell: |
    yum-config-manager --enable epel
    yum-config-manager --enable OpenHPC
    yum-config-manager --enable OpenHPC-updates

- name: Install yum-config-manager on the image
  yum:
    installroot: /install/netboot/centos7.6/x86_64/compute/rootimg
    disablerepo: '*'
    enablerepo: C7.6.1810-base
    name: yum-utils
    state: present

- name: Enable required repositories in the image too
  shell: |
    chroot /install/netboot/centos7.6/x86_64/compute/rootimg yum-config-manager --enable epel
    chroot /install/netboot/centos7.6/x86_64/compute/rootimg yum-config-manager --enable OpenHPC
    chroot /install/netboot/centos7.6/x86_64/compute/rootimg yum-config-manager --enable OpenHPC-updates

- name: Install the base and documentation packages
  yum:
    state: present
    name:
      - ohpc-base
      - docs-ohpc

- name: Check if NTP is running
  systemd:
    name: chronyd
    state: started

- name: Export the required filesystems over NFS
  copy:
    dest: /etc/exports
    content: |
      /home *(rw,no_subtree_check)
      /opt/ohpc/pub *(ro)

- import_tasks: automount.yml
- import_tasks: image.yml

# mkdir -p /install/custom/netboot/centos7.6/
# cat <<EOF >> /install/custom/netboot/centos7.6/compute.pkglist
# ohpc-base-compute
# lmod-ohpc
# chrony
# EOF
# chdef -t osimage -o centos7.6-x86_64-netboot-compute -p pkglist=/install/custom/netboot/compute.synclist
# chdef -t osimage -o centos7.6-x86_64-netboot-compute -p pkgdir='http://download.fedoraproject.org/pub/epel/7/x86_64,http://build.openhpc.community/OpenHPC:/1.3/CentOS_7,http://build.openhpc.community/OpenHPC:/1.3/updates/CentOS_7'
#
# mkdir -p /install/custom/postinstall/centos7.6/
# cat <<EOF > /install/custom/postinstall/centos7.6/chrony-config.sh
# sed -i s/0.centos.pool.ntp.org/headnode.cluster.example.com/ $IMG_ROOTIMGDIR/etc/chrony.conf
# sed -i /centos.pool/d $IMG_ROOTIMGDIR/etc/chrony.conf
# EOF
# chmod +x /install/custom/postinstall/centos7.6/chrony-config.sh
# chdef -t osimage -o centos7.6-x86_64-netboot-compute -p postinstall=/install/custom/postinstall/centos7.6/chrony-config.sh
#
# genimage centos7.6-x86_64-netboot-compute
