---
- name: Converge
  hosts: all
  roles:
    - role: postfix
      vars:
        postfix_install: yes
        postfix_profile: local
        cluster_name: 'newcluster'
        domain_name: 'clusterdomain'
        fqdn: '{{ cluster_name }}.{{ domain_name }}'
        sms_network: 10.1.0.0/16
        postfix_myhostname: '{{ cluster_name }}'
        postfix_mydomain: '{{ domain_name }}'
        postfix_mydestination: []
        postfix_mynetworks:
          - 127.0.0.0/8
          - '{{ sms_network }}'
        postfix_mynetworks_more: '192.168.123.0/24, 172.21.1.0/24'
        postfix_relayhost: '127.0.0.1'
        postfix_sasl_user: postfix_sasl_user
        postfix_sasl_password: postfix_sasl_password
        postfix_sasl_server: postfix_sasl_server
        postfix_sasl_port: 25
