- name: Update playbook from git
  shell: |
    git pull --rebase
  delegate_to: localhost
  register: git
  # failed_when: git.rc != 0 and git.stderr is not search('You have unstaged changes')
  ignore_errors: yes

- name: Download submodules
  shell: |
    git submodule init
    git submodule update
  delegate_to: localhost
  ignore_errors: yes

- name: Install dependencies
  yum:
    name:
      - python-netaddr

- name: Gather facts
  setup:
    gather_subset:
      - all

- name: Check that the provided interfaces exists
  assert:
    that:
      - '"{{ item }}" in ansible_interfaces'
  loop:
    - "{{ sms_eth_external }}"
    - "{{ sms_eth_internal }}"

- import_tasks: check-nodes-yaml.yaml
