- name: Install xcat-core repo
  yum_repository:
    name: xcat-core
    file: xcat-core
    description: xcat-core
    baseurl: http://xcat.org/files/xcat/repos/yum/latest/xcat-core # latest here is lated xCAT
    enabled: yes
    gpgcheck: yes
    gpgkey: http://xcat.org/files/xcat/repos/yum/latest/xcat-core/repodata/repomd.xml.key

- name: Install xcat-dep repo
  yum_repository:
    name: xcat-dep
    file: xcat-dep
    description: xcat-dep
    baseurl: http://xcat.org/files/xcat/repos/yum/latest/xcat-dep/rh$releasever/$basearch
    enabled: yes
    gpgcheck: yes
    gpgkey: http://xcat.org/files/xcat/repos/yum/latest/xcat-dep/rh$releasever/$basearch/repodata/repomd.xml.key
