- name: Install EPEL repository
  yum:
    name: epel-release
    state: present

- name: OpenHPC
  yum:
    state: present
    name: https://github.com/openhpc/ohpc/releases/download/v1.3.GA/ohpc-release-1.3-1.el7.x86_64.rpm

- name: Install Mellanox repository
  yum_repository:
    file: mellanox_mlnx_ofed_dpdk_upstream_libs
    name: mlnx_ofed_dpdk_upstream_libs_latest
    description: Mellanox Technologies rhel7.6-$basearch mlnx_ofed_dpdk_upstream_libs latest version
    enabled: yes
    gpgkey: http://www.mellanox.com/downloads/ofed/RPM-GPG-KEY-Mellanox
    gpgcheck: yes
    baseurl: http://linux.mellanox.com/public/repo/mlnx_ofed_dpdk_upstream_libs/latest/rhel7.6/$basearch

- name: Install Mellanox upstream libs repository
  yum_repository:
    file: mellanox_mlnx_ofed_dpdk_upstream_libs
    name: mlnx_ofed_dpdk_upstream_libs_4.6-3.5.8.0_base
    description: Mellanox Technologies rhel7.6-$basearch mlnx_ofed_dpdk_upstream_libs 4.6-3.5.8.0 GA
    baseurl: http://linux.mellanox.com/public/repo/mlnx_ofed_dpdk_upstream_libs/4.6-3.5.8.0/rhel7.6/$basearch
    enabled: no
    gpgkey: http://www.mellanox.com/downloads/ofed/RPM-GPG-KEY-Mellanox
    gpgcheck: yes

- name: Install xcat-core repo
  yum_repository:
    name: xcat-core
    file: xcat-core
    description: xcat-core
    baseurl: http://xcat.org/files/xcat/repos/yum/latest/xcat-core # latest here is lated xCAT
    enabled: yes
    gpgcheck: yes
    gpgkey: http://xcat.org/files/xcat/repos/yum/latest/xcat-core/repodata/repomd.xml.key

- name: Install xcat-dep repo
  yum_repository:
    name: xcat-dep
    file: xcat-dep
    description: xcat-dep
    baseurl: http://xcat.org/files/xcat/repos/yum/latest/xcat-dep/rh$releasever/$basearch
    enabled: yes
    gpgcheck: yes
    gpgkey: http://xcat.org/files/xcat/repos/yum/latest/xcat-dep/rh$releasever/$basearch/repodata/repomd.xml.key
