- name: Log iso
  debug: msg="ISO file = {{ iso_path }}{{ centos_iso }}"

- name: Check for ISO
  stat:
    path: '{{ iso_path }}{{ centos_iso }}'
  register: iso
  tags:
    - 'iso'

- name: Download CentOS
  get_url:
    # url: http://mirror.cc.if.ufrj.br/iso/CentOS-7-x86_64-DVD-1810.iso
    url: http://ftp.unicamp.br/pub/centos/{{ centos_version }}/isos/x86_64/{{ centos_iso }}
    dest: '{{ iso_path }}{{ centos_iso }}'
  when: not iso.stat.exists
  async: 6000
  retry: 3
  poll: 60
  tags:
    - 'iso'

- name: "Run copycds on {{ centos_iso }}"
  shell: |
    source /etc/profile.d/xcat.sh
    copycds {{ iso_path }}{{ centos_iso }}
    genimage {{ genimage_name }}
    packimage {{ genimage_name }}
  async: 1200
  poll: 0
  register: copycds
  tags:
    - 'genimage'

- name: Create VersatusHPC diretories
  file:
    state: directory
    mode: '0755'
    path: '{{ opencattus_path }}/{{ item }}'
  tags:
    - pkglist
    - postinstall
    - postscripts
  loop:
    - xcat
    - xcat/postscripts
    - xcat/postinstall
    - etc

- name: Create keys
  shell: |
    ssh-keygen -t {{ item }} -f {{ opencattus_path }}/xcat/ssh_host_{{ item }}_key -N '' <<< y
  args:
    creates: '{{ opencattus_path }}/xcat/ssh_host_{{ item }}_key'
  loop: '{{ ssh_key_types }}'
  tags:
    - postinstall
    - ssh_keys

- name: Fix ssh keys permissions
  file:
    path: "{{ opencattus_path }}/xcat/ssh_host_{{ item }}_key"
    group: ssh_keys
    mode: '0640'
  loop: "{{ ssh_key_types }}"
  tags:
    - postinstall
    - ssh_keys

- name: Create links
  file:
    state: link
    src: "{{ opencattus_path }}/xcat/postscripts"
    dest: /install/postscripts/opencattus
  tags:
    - postscripts

- name: Create add-cluster-key.sh postinstall
  tags:
    - postinstall
  copy:
    dest: "{{ opencattus_path }}/xcat/postinstall/add-cluster-key"
    mode: '0755'
    content: |
      #!/bin/bash

      echo "=======> Post install $0 started"

      pubkey=$(cat ~/.ssh/id_ed25519.pub)
      authorized_keys="$IMG_ROOTIMGDIR/root/.ssh/authorized_keys"
      if [ ! -f $authorized_keys ]; then
          mkdir -p $IMG_ROOTIMGDIR/root/.ssh || : # ignore error
          chmod 0700 $IMG_ROOTIMGDIR/root/.ssh
          echo "$pubkey" >> $authorized_keys
      else
          grep "$pubkey" $authorized_keys || echo "$pubkey" >> $authorized_keys
      fi

- name: Create create-ssh-key postinstall
  tags:
    - postinstall
  copy:
    dest: "{{ opencattus_path }}/xcat/postinstall/create-ssh-key"
    mode: '0755'
    content: |
      #!/bin/bash -eu
      set -o pipefail
      echo "=======> Post install $0 started"
      \cp -vf {{ opencattus_path }}/xcat/ssh_host_* $IMG_ROOTIMGDIR/etc/ssh/
      SSH_GID=`chroot ${IMG_ROOTIMGDIR} getent group ssh_keys | cut -f3 -d:`
      chown 0:$SSH_GID ${IMG_ROOTIMGDIR}/etc/ssh/ssh_host_*_key
      chmod 640 ${IMG_ROOTIMGDIR}/etc/ssh/ssh_host_*_key

- name: Add freeipa-client to the image
  blockinfile:
    create: yes
    path: '{{ pkglist }}'
    block: |
      #NEW_INSTALL_LIST#
      freeipa-client
  tags:
    - pkglist

- name: Wait genimage to finish
  async_status:
    jid: "{{ copycds.ansible_job_id }}"
  register: wait
  until: wait.finished
  poll: 30
  retries: 300
  delay: 30
  tags:
    - 'genimage'

- name: Add postinstall to the image
  shell: |
    source /etc/profile.d/xcat.sh
    chdef -t osimage -o {{ genimage_name }} -p postinstall={{ opencattus_path }}/xcat/postinstall/add-cluster-key
  tags:
    - postinstall

- name: Create a base image for debugging
  shell: |
    set -o pipefail
    source /etc/profile.d/xcat.sh
    chdef -z <<EOF
    # <xCAT data object stanza file>

    {{ genimage_name }}-base:
        objtype=osimage
        exlist=/opt/xcat/share/xcat/netboot/centos/compute.centos{{ el_major_version }}.exlist
        imagetype=linux
        osarch=x86_64
        osdistroname=centos{{ el_version }}-x86_64
        osname=Linux
        osvers=centos{{ el_version }}
        otherpkgdir=/install/post/otherpkgs/centos{{ el_version }}/x86_64
        permission=755
        pkgdir=/install/centos{{ el_version }}/x86_64
        postscripts=
        postinstall=/opt/xcat/share/xcat/netboot/centos/compute.centos{{ el_major_version }}.postinstall,/opt/opencattus/xcat/postinstall/add-cluster-key,/opt/opencattus/xcat/postinstall/create-ssh-key
        profile=compute
        provmethod=netboot
        rootimgdir=/install/netboot/centos{{ el_version }}/x86_64/compute-base
        synclists=/opt/opencattus/xcat/compute.synclist
    EOF
  tags:
    - osimage
  register: chdef
  changed_when: chdef.rc == 0 and chdef.stdout is search("New object definitions")

- name: Add compute.pkglist to the image
  shell: |
    source /etc/profile.d/xcat.sh
    chdef -t osimage -o {{ genimage_name }} -p pkglist={{ pkglist }}
  tags:
    - pkglist
    - genimage

- name: Add repositories to the image
  shell: |
    source /etc/profile.d/xcat.sh
    chdef -t osimage -o {{ genimage_name }} -p pkgdir={{ item }}
  loop:
    # - http://vault.centos.org/7.6.1810/os/x86_64/
    # - http://vault.centos.org/7.6.1810/updates/x86_64/
    # - http://vault.centos.org/7.6.1810/extras/x86_64/
    - http://mirror.centos.org/centos/{{ el_major_version }}/os/x86_64/
    - http://mirror.centos.org/centos/{{ el_major_version }}/updates/x86_64/
    - http://mirror.centos.org/centos/{{ el_major_version }}/extras/x86_64/
    - http://mirror.centos.org/centos/{{ el_major_version }}/centosplus/x86_64/
    - http://download.fedoraproject.org/pub/epel/{{ el_major_version }}/x86_64
    - http://build.openhpc.community/OpenHPC:/{{ ohpc_version }}/CentOS_{{ el_major_version }}
    - http://build.openhpc.community/OpenHPC:/{{ ohpc_version }}/updates/CentOS_{{ el_major_version }}
  tags:
    - postinstall

- name: Add postinstall for Create keys
  shell: |
    source /etc/profile.d/xcat.sh
    chdef -t osimage -o {{ genimage_name }} -p postinstall={{ opencattus_path }}/xcat/postinstall/create-ssh-key
  tags:
    - postinstall

- name: Configure Infiniband
  when: ib_stack != "none"
  include_tasks: roles/infiniband/tasks/{{ ib_stack }}-image.yaml
